# Generated by Django 3.2.15 on 2024-10-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=200, verbose_name='收件人')),
                ('subject', models.CharField(max_length=200, verbose_name='主题')),
                ('body', models.TextField(verbose_name='正文')),
                ('sent_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('sender', models.CharField(max_length=200, verbose_name='发件人')),
            ],
            options={
                'verbose_name': '邮件',
                'verbose_name_plural': '邮件',
            },
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('time', models.CharField(default='', max_length=50, verbose_name='登陆时间')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='问题')),
                ('description', models.TextField(verbose_name='问题描述')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='邮箱')),
                ('bio', models.CharField(max_length=500, null=True, verbose_name='个人介绍')),
                ('avatar', models.CharField(max_length=200, null=True, verbose_name='头像url')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='上次登录时间')),
                ('password_question', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码问题')),
                ('password_answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码问题答案')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='答案')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.question')),
            ],
        ),
    ]
