# Generated by Django 3.2.15 on 2024-10-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20241002_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='圈子名')),
                ('description', models.TextField(null=True, verbose_name='圈子描述')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否付费圈子')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('max_members', models.IntegerField(default=12, verbose_name='成员最大数量')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_loops', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='LoopMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('is_banned', models.BooleanField(default=False, verbose_name='是否被禁')),
                ('role', models.CharField(choices=[('member', '成员'), ('admin', '管理员')], default='member', max_length=20, verbose_name='角色')),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='myapp.loop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loops', to='myapp.user')),
            ],
            options={
                'unique_together': {('loop', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
        migrations.AddField(
            model_name='post',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='价格范围'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.AddField(
            model_name='post',
            name='loop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.loop'),
        ),
    ]
