# Generated by Django 3.2.15 on 2024-10-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20241008_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cuisine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='菜系'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='backer_logs/', verbose_name='图片'),
        ),
    ]
