# Generated by Django 5.1.2 on 2024-10-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_auto_20241008_0601"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="price_range",
            field=models.TextField(
                blank=True, max_length=50, null=True, verbose_name="均价"
            ),
        ),
    ]
