# Generated by Django 5.1.2 on 2024-11-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_splitbill_splitbillparticipant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="rating",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="评分"
            ),
        ),
    ]
